name: "Release tag"
on:
  push:
    tags:
      - v*

env:
  GO_VERSION: '1.20'

jobs:
  release:
    name: Release artifacts
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SN_EXPORT_TO_FOLDER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Create release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.SN_EXPORT_TO_FOLDER_TOKEN }}
